language: go
dist: trusty

go:
  - 1.13.x
  - 1.x

notifications:
  email:
    on_success: never
    on_failure: change

env:
  global:
    - GO111MODULE: on
    - VERSION: $TRAVIS_TAG

go_import_path: github.com/containous/whoamiudp

before_install:
  # Install linters and misspell
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.15.0
  - golangci-lint --version


install:
  - echo "TRAVIS_GO_VERSION=$TRAVIS_GO_VERSION"
  - make dependencies
